version: "3.1"
services:
  rest:
    image: ailabreg.changeme.ac.kr/rest-oracle:latest
    environment:
    - TZ=Asia/Seoul
    - LANG=ko_KR.UTF-8
    - DB_USER=dbuser
    # - PASSWORD=/run/secrets/PASSWORD for HA config
    - DB_PASSWORD=${DB_PASSWORD}
    - SERVICE=XEPDB1
    - HOST=13.209.18.89
    - DB_PORT=32118
    - DB_TYPE=oracle
    - AUTH_QUERY=SELECT FIRST_NAME AS "surname", LAST_NAME AS "givenName", CONCAT(FIRST_NAME, LAST_NAME) AS "displayName", USERNAME AS "uid", EMAIL AS "mail", EMPLOYEE_NUMBER AS "employeeNumber", '빛가람대학교' as "organizationName",  DEPARTMENT as "organizationalUnitName", EMPLOYEE_TYPE as "employeeType" FROM DBUSER.USERS WHERE username = :USERID and PASSWORD=DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW(:PASSWORD, 'AL32UTF8'), 4)
    - ATTRIBUTE_QUERY=SELECT FIRST_NAME AS "surname", LAST_NAME AS "givenName", CONCAT(FIRST_NAME, LAST_NAME) AS "displayName", USERNAME AS "uid", EMAIL AS "mail", EMPLOYEE_NUMBER AS "employeeNumber", '빛가람대학교' as "organizationName",  DEPARTMENT as "organizationalUnitName", EMPLOYEE_TYPE as "employeeType" FROM DBUSER.USERS WHERE username = :USERID
    # secrets:
      # DB_PASSWORD
    networks:
        idpapp:
            aliases:
             - rest
  idp:
    build:
      context: ./
    image:  ailabreg.changeme.ac.kr/${REALM}/shibboleth-idp:latest
    # image:  jnu-idp:latest
    environment:
     - TZ=Asia/Seoul
     - LANG=ko_KR.UTF-8
    ports:
    - 443:443
    - 80:80
    depends_on:
     - rest
    networks:
        idpapp:
    # secrets: #for HA
    # - DB_PASSWORD
    # - REALM
    # volumes:
      # - ./logs:/opt/shib-jetty-base/logs
    # deploy:
    #     mode: replicated
    #     replicas: 2
networks:
    idpapp:

secrets:
    DB_PASSWORD:
      file: DB_PASSWORD.txt
    REALM:
      file: REALM.txt
